cryptoflow:
  name: "CryptoFlow"
  version: "1.0.0"

channels:
  raw_buffer: 100
  processed_buffer: 100
  write_buffer: 100

reader:
  max_workers: 1
  timeout: "5s"

processor:
  max_workers: 1
  batch_size: 1
  batch_timeout: "1s"

exchanges:
  binance:
    enabled: true
    base_url: "https://fapi.binance.com"
    endpoints:
      - name: "futures_depth"
        path: "/fapi/v1/depth"
        limit: 5
        interval_ms: 1000
        symbols: ["BTCUSDT"]
        timeout: "5s"
    connection_pool:
      max_idle_conns: 10
      max_conns_per_host: 10
      idle_conn_timeout: "90s"

storage:
  s3:
    enabled: true
    bucket: "cryptoflow-test"
    region: "us-east-1"
    endpoint: "http://localhost:9000"
    path_style: true

writer:
  max_workers: 1
  batch:
    size: 10
    timeout: "1s"
    max_memory: "1MB"
  buffer:
    max_size: 10
    flush_interval: "1s"
    memory_threshold: 0.8
  partitioning:
    scheme: "time"
    time_format: "year={year}/month={month}/day={day}/hour={hour}"
    additional_keys: ["exchange", "symbol"]
  formats:
    parquet:
      enabled: true
      compression: "snappy"
      page_size: 0
    avro:
      enabled: false
      compression: ""
  compression: ""

logging:
  level: "info"
  format: "json"
  output: "stdout"
