version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mrhadipinova/cryptoflow:latest 
    container_name: cryptoflow              
    restart: unless-stopped
    env_file:
      - .env
    command: ["./cryptoflow"]
