  version: '3.8'
  services:
    cryptoflow:
      build: .
      container_name: mrhadipinova/cryptoflow:latest
      ports:
        - "2112:2112"
      restart: unless-stopped
      volumes:
        - ./data:/app/data
