version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #image: mrhadipinova/cryptoflow:latest 
    container_name: cryptoflow              
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - S3_BUCKET
      - LOG_LEVEL=${LOG_LEVEL:-warn}
    command: ["./cryptoflow"]
