version: "3.8"

networks:
  kafka-net:

services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.8.0
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    networks: [kafka-net]

  kafka1:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      # Listeners
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # ZK
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"

      # Broker basics
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # Logging + JMX
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}

      # Simple local ACL posture
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"

      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      # IMPORTANT: Metrics Reporter REMOVED for cp-kafka (prevents ClassNotFound)
      # KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      # CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka1:19092"
      # CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: "1"
      # CONFLUENT_METRICS_REPORTER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      # CONFLUENT_METRICS_REPORTER_SECURITY_PROTOCOL: "PLAINTEXT"
    depends_on:
      - zoo1
    networks: [kafka-net]

  schema-registry:
    image: confluentinc/cp-schema-registry:7.8.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka1
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka1:19092"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    networks: [kafka-net]

  ksqldb:
    image: confluentinc/cp-ksqldb-server:7.8.0
    hostname: ksqldb
    container_name: ksqldb
    depends_on:
      - kafka1
      - schema-registry
    ports:
      - "8088:8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: "kafka1:19092"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_KSQL_SERVICE_ID: "ksql_svc_01"
      KSQL_KSQL_STREAMS_STATE_DIR: "/tmp/ksql-state"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_STREAMS_AUTO_OFFSET_RESET: "earliest"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_HEAP_OPTS: "-Xms512m -Xmx1024m"
      KSQL_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    networks: [kafka-net]

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.8.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka1
      - ksqldb
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka1:19092"

      # ksqlDB (internal + browser link)
      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb:8088"
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"

      # Schema Registry (internal + browser link)
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_SCHEMA_REGISTRY_ADVERTISED_URL: "http://localhost:8081"

      # Single-node friendly
      CONTROL_CENTER_REPLICATION_FACTOR: "1"
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: "1"
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: "1"
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: "1"
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: "1"

      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      CONTROL_CENTER_HEAP_OPTS: "-Xms512m -Xmx1024m"
    networks: [kafka-net]
