services:
  app:
    build:
      context: ../..
      dockerfile: ./infra/docker/Dockerfile
    #image: mrhadipinova/cryptoflow:latest
    container_name: cryptoflow
    restart: unless-stopped
    network_mode: host
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - S3_BUCKET
      - LOG_LEVEL=${LOG_LEVEL:-warn}
      - APP_ENV=${APP_ENV:-development}
    command: ["./cryptoflow"]
