shards:
  - ip: 172.31.3.251
    binance_symbols:
     - BTCUSDT
     - XRPUSDT
     - BNBUSDT
    kucoin_symbols:
      - XBTUSDTM
      - XRPUSDTM
      - BNBUSDTM
      - ONDOUSDTM
  - ip: 172.31.8.202
    binance_symbols:
      - SEIUSDT
      - ETHUSDT
      - 1000SHIBUSDT
    kucoin_symbols:
      - SEIUSDTM
      - ETHUSDTM
      - SUIUSDTM
      - SHIBUSDTM
  - ip: 172.31.1.88
    binance_symbols:
      - SOLUSDT
      - DOTUSDT
      - 1000PEPEUSDT
      - DOGEUSDT
    kucoin_symbols:
      - SOLUSDTM
      - DOTUSDTM
      - PEPEUSDTM
      - DOGEUSDTM
  - ip: 172.31.14.157
    binance_symbols:
      - WIFUSDT
      - ADAUSDT
      - BTCUSDC
      - ETHUSDC
    kucoin_symbols:
      - WIFUSDTM
      - ADAUSDTM
      - XBTUSDCM
      - ETHUSDCM
  - ip: 172.31.9.173
    binance_symbols:
      - SOLUSDC
      - SUIUSDC
      - XRPUSDC
      - LTCUSDT
    kucoin_symbols:
      - SOLUSDCM
      - SUIUSDCM
      - XRPUSDCM
      - LTCUSDTM
  - ip: 172.31.4.116
    binance_symbols:
      - AVAXUSDT
      - LINKUSDT
      - UNIUSDT
      - XLMUSDT
    kucoin_symbols:
      - AVAXUSDTM
      - LINKUSDTM
      - UNIUSDTM
      - XLMUSDTM
  - ip: 172.31.8.67
    binance_symbols:
      - NEARUSDT
      - HYPEUSDT
      - BCHUSDT
      - TRXUSDT
    kucoin_symbols:
      - NEARUSDTM
      - HYPEUSDTM
      - BCHUSDTM
      - TRXUSDTM
  - ip: 172.31.5.194
    binance_symbols:
      - AAVEUSDT
      - 1000BONKUSDT
      - OPUSDT
      - ARBUSDT
    kucoin_symbols:
      - AAVEUSDTM
      - OPUSDTM
      - ARBUSDTM
      - INJUSDTM
  - ip: 172.31.15.240
    binance_symbols:
      - INJUSDT
      - FARTCOINUSDT
      - ONDOUSDT
      - SUIUSDT
