shards:
  - ip: 172.31.1.88
    binance_symbols:
      - BTCUSDT
      - ETHUSDT
      - BNBUSDT
      - XRPUSDT
    kucoin_symbols:
      - BTCUSDTM
      - ETHUSDTM
      - BNBUSDTM
      - XRPUSDTM
  - ip: 172.31.14.157
    binance_symbols:
      - DOTUSDT
      - DOGEUSDT
      - ADAUSDT
      - SOLUSDT
    kucoin_symbols:
      - DOTUSDTM
      - DOGEUSDTM
      - ADAUSDTM
      - SOLUSDTM
