shards:
  - ip: 172.31.9.173
    binance_symbols:
      - BTCUSDT
      - ETHUSDT
    kucoin_symbols:
      - XBTUSDTM
      - ETHUSDTM
  - ip: 172.31.14.157
    binance_symbols:
      - DOTUSDT
      - XRPUSDT
    kucoin_symbols:
      - DOTUSDTM
      - XRPUSDTM
