services:
  app:
    build:
      context: ../..
      dockerfile: ./infra/podman/Containerfile
    container_name: cryptoflow
    restart: unless-stopped
    network_mode: host
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - S3_BUCKET
      - LOG_LEVEL=${LOG_LEVEL:-warn}
#      - APP_ENV=${APP_ENV:-production}
    command: ["./cryptoflow"]
