name: Deploy Collector Dashboard

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
    steps:
      - uses: actions/checkout@v4
      - name: Push dashboard to CloudWatch
        run: |
          aws cloudwatch put-dashboard \
            --dashboard-name Data \
            --dashboard-body file://infra/cloudwatch/collector-dashboard.json