name: Deploy Production (manual)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'deploy' to confirm the production release"
        required: true
        default: deploy

concurrency:
  group: deploy-production
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build & Deploy to production
    if: github.ref == 'refs/heads/main' && github.event.inputs.confirm == 'deploy'
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      APP_DIR: /home/${{ secrets.EC2_USER }}/cryptoflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build binary
        run: go build -o cryptoflow .

      - name: Ensure remote workspace exists
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            mkdir -p "$APP_DIR"
            cd "$APP_DIR"
            find . -mindepth 1 -maxdepth 1 ! -name '.env' ! -name 'data' -exec rm -rf {} +

      - name: Upload application bundle
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".,cryptoflow"
          target: "$APP_DIR"

      - name: Restart services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            cd "$APP_DIR/infra/podman"
            export APP_ENV=production
            if ! command -v podman >/dev/null 2>&1; then
              echo "Podman is not installed on the target host." >&2
              exit 1
            fi
            compose_file="podman-compose.production.yml"
            if podman compose version >/dev/null 2>&1; then
              podman compose -f "$compose_file" down --remove-orphans || true
              podman compose -f "$compose_file" up -d --build
            elif command -v podman-compose >/dev/null 2>&1; then
              podman-compose -f "$compose_file" down --remove-orphans || true
              podman-compose -f "$compose_file" up -d --build
            else
              echo "Neither 'podman compose' nor 'podman-compose' is available on the target host." >&2
              exit 1
            fi

